import { generateWithGemini } from '../lib/gemini';
import { LegalAdvisorResponse, LegalCategory } from '../types/agents';

const DEFAULT_ADVISOR_RESPONSE: LegalAdvisorResponse = {
  rights: [],
  actions: [],
  notes: [],
  text: 'Legal advice generation failed due to a malformed response. Please consult a legal professional. (Standard Disclaimer: This information is generated by AI and does not constitute formal legal counsel.)'
};

const SYSTEM_INSTRUCTION = `You are a legal advisor assistant. Keep responses extremely concise, using simple terms and short bullet points. Limit text to essential legal guidance.
Include a standard disclaimer at the end of 'text'.
Output JSON only:
{
  rights: string[];   // short bullet points of key rights
  actions: string[];  // short bullet points of practical actions
  notes: string[];    // short bullet points of warnings or precautions
  text: string;       // concise explanation in simple terms, ending with the disclaimer
}`;

export async function runAdvisorAgent(
  userQuery: string,
  category: LegalCategory,
  documentAnalysis?: string,
  language: 'en' | 'hi' | 'gu' = 'en'
): Promise<LegalAdvisorResponse> {
  const langName = language === 'hi' ? 'Hindi' : language === 'gu' ? 'Gujarati' : 'English';
  
  const prompt = `User Query: "${userQuery}"
Category: "${category}"
${documentAnalysis ? `Document Analysis Context: \n${documentAnalysis}` : ''}

Analyze this context. Explain the user's legal rights, what actions they can take, and any warnings. Format the response as JSON.
IMPORTANT: You must translate and write all your output fields (rights, actions, notes, and explanation text) in ${langName}. The standard legal disclaimer at the end of 'text' must also be in ${langName}.`;

  const rawResponse = await generateWithGemini(prompt, {
    systemInstruction: SYSTEM_INSTRUCTION,
    jsonMode: true
  });

  console.log("ADVISOR_RAW_RESPONSE", rawResponse);

  if (!rawResponse || !rawResponse.trim()) {
    console.log("ADVISOR_RESPONSE_TYPE: Empty Content");
    return DEFAULT_ADVISOR_RESPONSE;
  }

  let cleaned = rawResponse.trim();
  let responseType = "Plain Text";

  // 1. Strip markdown fences or extract JSON substring
  const jsonMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (jsonMatch) {
    cleaned = jsonMatch[1].trim();
    responseType = "Markdown-wrapped JSON";
  } else {
    const startIndex = Math.min(
      cleaned.indexOf('{') !== -1 ? cleaned.indexOf('{') : Infinity,
      cleaned.indexOf('[') !== -1 ? cleaned.indexOf('[') : Infinity
    );
    const endIndex = Math.max(
      cleaned.lastIndexOf('}'),
      cleaned.lastIndexOf(']')
    );
    if (startIndex !== Infinity && endIndex !== -1 && endIndex > startIndex) {
      cleaned = cleaned.substring(startIndex, endIndex + 1).trim();
      responseType = "Valid JSON (with potential surrounding text)";
    }
  }

  // 2. Try parsing
  try {
    const parsed = JSON.parse(cleaned);
    if (responseType === "Plain Text") {
      responseType = "Valid JSON";
    }
    console.log(`ADVISOR_RESPONSE_TYPE: ${responseType}`);
    
    const finalParsed: LegalAdvisorResponse = {
      rights: Array.isArray(parsed.rights) ? parsed.rights : [],
      actions: Array.isArray(parsed.actions) ? parsed.actions : [],
      notes: Array.isArray(parsed.notes) ? parsed.notes : [],
      text: typeof parsed.text === 'string' ? parsed.text : JSON.stringify(parsed)
    };
    
    console.log("ADVISOR_PARSED_RESPONSE", finalParsed);
    return finalParsed;
  } catch (err: any) {
    console.log("ADVISOR_JSON_PARSE_ERROR", err.message);
    
    // Attempt basic JSON repair
    try {
      let repaired = cleaned.replace(/,\s*}/g, '}').replace(/,\s*]/g, ']');
      repaired = repaired.replace(/"([^"]*)"/g, (match, p1) => {
        const escaped = p1.replace(/\n/g, '\\n').replace(/\r/g, '\\r');
        return `"${escaped}"`;
      });
      const parsedRepaired = JSON.parse(repaired);
      console.log("ADVISOR_RESPONSE_TYPE: Repaired JSON");
      
      const finalParsed: LegalAdvisorResponse = {
        rights: Array.isArray(parsedRepaired.rights) ? parsedRepaired.rights : [],
        actions: Array.isArray(parsedRepaired.actions) ? parsedRepaired.actions : [],
        notes: Array.isArray(parsedRepaired.notes) ? parsedRepaired.notes : [],
        text: typeof parsedRepaired.text === 'string' ? parsedRepaired.text : JSON.stringify(parsedRepaired)
      };
      
      console.log("ADVISOR_PARSED_RESPONSE", finalParsed);
      return finalParsed;
    } catch (repairErr: any) {
      console.log("ADVISOR_REPAIR_ERROR", repairErr.message);
    }

    // Fall back to plain text if JSON parsing fails and response is not empty
    console.log("ADVISOR_RESPONSE_TYPE: Plain Text (Fallback)");
    const fallbackParsed: LegalAdvisorResponse = {
      rights: [],
      actions: [],
      notes: [],
      text: rawResponse.trim()
    };
    console.log("ADVISOR_PARSED_RESPONSE", fallbackParsed);
    return fallbackParsed;
  }
}
